"""Streamlit page showing builder config."""
import asyncio
from typing import cast

import streamlit as st
from streamlit_pills import pills

from agent_utils import RAGAgentBuilder

####################
#### STREAMLIT #####
####################



st.set_page_config(page_title="Generated RAG Agent", page_icon="🦙", layout="centered", initial_sidebar_state="auto", menu_items=None)
st.title("Generated RAG Agent")
st.info(
    "This is generated by the builder in the above section.", icon="ℹ️"
)

# Streamlit runs in a separate thread that doesn’t have an event loop by default
# Create an event loop and run the async functions inside it
try:
    loop = asyncio.get_event_loop_policy().get_event_loop()
    if loop.is_closed():
        raise RuntimeError
except RuntimeError:
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)


if "agent_messages" not in st.session_state.keys(): # Initialize the chat messages history
    st.session_state.agent_messages = [
        {"role": "assistant", "content": "Ask me a question!"}
    ]

def add_to_message_history(role, content):
    message = {"role": role, "content": str(content)}
    st.session_state.agent_messages.append(message) # Add response to message history


agent = None
if "agent_builder" in st.session_state.keys():
    agent_builder = cast(RAGAgentBuilder, st.session_state.agent_builder)
    if agent_builder.cache.agent is not None:
        agent = agent_builder.cache.agent
        for message in st.session_state.agent_messages: # Display the prior chat messages
            with st.chat_message(message["role"]):
                st.write(message["content"])

        # don't process selected for now
        if prompt := st.chat_input("Your question"): # Prompt for user input and save to chat history
            add_to_message_history("user", prompt)
            with st.chat_message("user"):
                st.write(prompt)

        # If last message is not from assistant, generate a new response
        if st.session_state.agent_messages[-1]["role"] != "assistant":
            with st.chat_message("assistant"):
                with st.spinner("Thinking..."):
                    message_placeholder = st.empty() # Container for the response that's overwritten with each token
                    async def generate_response():
                        full_response = ""
                        response = st.session_state.builder_agent.stream_chat(prompt) # Stream responses to the frontend
                        for token in response.response_gen:
                            full_response += token or ""
                            message_placeholder.markdown(full_response)
                        return full_response
                    
                    full_response = asyncio.run(generate_response())
                    add_to_message_history("assistant", full_response)
    else:
        st.info("Agent not created. Please create an agent in the above section.")
else:
    st.info("Agent not created. Please create an agent in the above section.")
